//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadaniaLaboratoryjne
    {
        public int Id_bad_lab { get; set; }
        public string Kod { get; set; }
        public Nullable<int> Przydz_Kierow { get; set; }
        public Nullable<int> Przydz_lab { get; set; }
        public Nullable<int> Id_wizyty { get; set; }
        public string Uwagi_lek { get; set; }
        public System.DateTime Dat_zlec { get; set; }
        public string Wynik { get; set; }
        public Nullable<System.DateTime> Dat_wyk_anul { get; set; }
        public string Uwagi_kier { get; set; }
        public Nullable<System.DateTime> Dat_zatw_anul { get; set; }
        public string Stat { get; set; }
    
        public virtual Wizyta Wizyta { get; set; }
        public virtual KierownikLab KierownikLab { get; set; }
        public virtual Laborant Laborant { get; set; }
        public virtual SlownikBadan SlownikBadan { get; set; }
    }
}
