//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadaniaFizyczne
    {
        public int Id_bad_fiz { get; set; }
        public Nullable<int> Id_wizyta { get; set; }
        public string Kod { get; set; }
        public string Wynik { get; set; }
    
        public virtual Wizyta Wizyta { get; set; }
        public virtual SlownikBadan SlownikBadan { get; set; }
    }
}
