//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PrzychodniaEntities : DbContext
    {
        public PrzychodniaEntities()
            : base("name=PrzychodniaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BadaniaFizyczne> BadaniaFizyczne { get; set; }
        public virtual DbSet<BadaniaLaboratoryjne> BadaniaLaboratoryjne { get; set; }
        public virtual DbSet<KierownikLab> KierownikLab { get; set; }
        public virtual DbSet<Laborant> Laborant { get; set; }
        public virtual DbSet<Lekarz> Lekarz { get; set; }
        public virtual DbSet<Logowanie> Logowanie { get; set; }
        public virtual DbSet<Pacjent> Pacjent { get; set; }
        public virtual DbSet<Rejestracja> Rejestracja { get; set; }
        public virtual DbSet<SlownikBadan> SlownikBadan { get; set; }
        public virtual DbSet<Wizyta> Wizyta { get; set; }
    }
}
