//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class SlownikBadan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SlownikBadan()
        {
            this.BadaniaFizyczne = new HashSet<BadaniaFizyczne>();
            this.BadaniaLaboratoryjne = new HashSet<BadaniaLaboratoryjne>();
        }
    
        public string Kod { get; set; }
        public string Typ { get; set; }
        public string Nazwa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BadaniaFizyczne> BadaniaFizyczne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BadaniaLaboratoryjne> BadaniaLaboratoryjne { get; set; }
    }
}
