//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wizyta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wizyta()
        {
            this.BadaniaFizyczne = new HashSet<BadaniaFizyczne>();
            this.BadaniaLaboratoryjne = new HashSet<BadaniaLaboratoryjne>();
        }
    
        public int Id_wiz { get; set; }
        public Nullable<int> Lek_wyk { get; set; }
        public Nullable<int> Id_pacj { get; set; }
        public string Opis { get; set; }
        public string Diagnoza { get; set; }
        public string Stat { get; set; }
        public System.DateTime Dat_rej { get; set; }
        public Nullable<System.DateTime> Dat_zak_anul { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BadaniaFizyczne> BadaniaFizyczne { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BadaniaLaboratoryjne> BadaniaLaboratoryjne { get; set; }
        public virtual Lekarz Lekarz { get; set; }
        public virtual Pacjent Pacjent { get; set; }
    }
}
