//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public int Id_adm { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    
        public virtual Logging Logging { get; set; }
    }
}
