//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.LaboratoryTests = new HashSet<LaboratoryTest>();
            this.PhysicalExaminations = new HashSet<PhysicalExamination>();
        }
    
        public int Id_app { get; set; }
        public Nullable<int> Id_reg { get; set; }
        public Nullable<int> Id_doc { get; set; }
        public Nullable<int> Id_pat { get; set; }
        public string Description { get; set; }
        public string Diagnosis { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Reg_date { get; set; }
        public Nullable<System.DateTime> End_date { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual Registration Registration { get; set; }
        public virtual AppointmentState AppointmentState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaboratoryTest> LaboratoryTests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhysicalExamination> PhysicalExaminations { get; set; }
    }
}
