//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LaboratoryManager()
        {
            this.LaboratoryTests = new HashSet<LaboratoryTest>();
        }
    
        public int Id_labM { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
    
        public virtual Logging Logging { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LaboratoryTest> LaboratoryTests { get; set; }
    }
}
