//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LaboratoryTest
    {
        public int Id_labTest { get; set; }
        public string Code { get; set; }
        public Nullable<int> Id_labManager { get; set; }
        public Nullable<int> Id_labTech { get; set; }
        public Nullable<int> Id_app { get; set; }
        public string DoctorsNote { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Result { get; set; }
        public Nullable<System.DateTime> RealizationDate { get; set; }
        public string ManagersNote { get; set; }
        public Nullable<System.DateTime> ManagersApprovalDate { get; set; }
        public string Status { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual LaboratoryManager LaboratoryManager { get; set; }
        public virtual LabTech LabTech { get; set; }
        public virtual MedicalGlossary MedicalGlossary { get; set; }
    }
}
