//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logging
    {
        public int Id_user { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
        public bool Active { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Doctor Doctor { get; set; }
        public virtual LaboratoryManager LaboratoryManager { get; set; }
        public virtual LabTech LabTech { get; set; }
        public virtual Registration Registration { get; set; }
    }
}
