//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalExamination
    {
        public int Id_exam { get; set; }
        public int Id_app { get; set; }
        public string Code { get; set; }
        public string Result { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual MedicalGlossary MedicalGlossary { get; set; }
    }
}
